import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Header from "./components/Header";

const roboto = Roboto({ subsets: ["latin"], weight:["300", "400", "500", "700", "900"] });

export const metadata: Metadata = {
  title: "MoviesFind",
  description: "Generated by Oscar Giraldo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {/* Components */}
        <Header></Header>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
